"""empty message

Revision ID: 1c53f8d794d9
Revises: 7fc955d73f1e
Create Date: 2020-04-23 16:26:15.065453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c53f8d794d9'
down_revision = '7fc955d73f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_table_tableInt'), 'table', ['tableInt'], unique=True)
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_table_tableInt'), table_name='table')
    # ### end Alembic commands ###
