"""empty message

Revision ID: 29124e6a6470
Revises: ae346256b650
Create Date: 2020-04-22 21:32:29.439302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29124e6a6470'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableInt', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_timestamp'), 'table', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_timestamp'), table_name='table')
    op.drop_table('table')
    # ### end Alembic commands ###
