"""empty message

Revision ID: 4dfffed89475
Revises: 79b33706580e
Create Date: 2020-04-23 11:49:03.157211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfffed89475'
down_revision = '79b33706580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('isBooked', sa.Boolean(), nullable=True))
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('table', 'isBooked')
    # ### end Alembic commands ###
