"""empty message

Revision ID: 79b33706580e
Revises: b505650a5b6b
Create Date: 2020-04-23 11:06:40.234169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b33706580e'
down_revision = 'b505650a5b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
