"""empty message

Revision ID: a0f6f5827e89
Revises: dfd1053e7e75
Create Date: 2020-04-23 09:47:33.647719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f6f5827e89'
down_revision = 'dfd1053e7e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
