"""empty message

Revision ID: b420f07cc21d
Revises: 5c24541415ed
Create Date: 2020-04-24 17:34:46.637675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b420f07cc21d'
down_revision = '5c24541415ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'timestamp')
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
