"""empty message

Revision ID: b505650a5b6b
Revises: c32439ba3482
Create Date: 2020-04-23 09:49:44.144436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505650a5b6b'
down_revision = 'c32439ba3482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
