"""empty message

Revision ID: c32439ba3482
Revises: a0f6f5827e89
Create Date: 2020-04-23 09:49:03.130774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32439ba3482'
down_revision = 'a0f6f5827e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
