"""empty message

Revision ID: dfd1053e7e75
Revises: 29124e6a6470
Create Date: 2020-04-23 09:43:36.893919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd1053e7e75'
down_revision = '29124e6a6470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_table_timestamp', table_name='table')
    op.drop_column('table', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_table_timestamp', 'table', ['timestamp'], unique=False)
    # ### end Alembic commands ###
